#!/bin/csh

# Following code to calculate multiple exponential HRF of different TAU
if ($# < 3) then
echo ""
echo "USAGE: $0:t This script will convolve a 1D file with a series of exponentials functions of different TAUs"
echo "USAGE: $0:t 1Dfile TR dtau maxtau"
echo "TR is the time of repetition, dtau is the interval between different TAU and maxtau is the maximum tau value desired"
echo "EXAMPLE:  $0:t pco2.1D 1.75 2 97"
echo "This will generate pco2w.1D file containing int(97/2) columns and same number of lines as pco2.1D"
echo ""
exit
endif

# Cleaning
rm -f MFUNC_gam.1D

# --- 1D files
set ref = $1


#--- USER INPUT -------------------
#-- TR: time of repetition in sec
set TR = $2

# -- Tau Interval in sec --
set dtau = $3

# -- Maximum TAU in sec
set maxtau = $4

# Calculate the number of reference waveform
set n_ref = `echo "(${maxtau})/$dtau" | bc`

# Construct a series of exponential function (MFUNC.1D) to do the convolution
makegam $TR $dtau $maxtau


# Calculate the convolved ref waveforms
rm -f tmpref1.1D
foreach n (`seq -f %02g 0 ${n_ref}`)
3dTsmooth -custom MFUNC_gam.1D\[$n\] {$ref}\'
cat smooth.1D | grep -v "#" >> tmpref1.1D
echo "----------------------------------------------$n"
end
1dcat tmpref1.1D\' > ${ref:r}_gam.1D
